/*
type設定したら、actionは自動になります。
例:
P_SIGNIN => pSigninAction
pSigninAction はactionのネームです。
*/
export const constantTypesAry = {
  ADD_PROJECT: 'ADD_PROJECT',
  EDIT_USERINFO: 'EDIT_USERINFO',
  GET_PROJECTS: 'GET_PROJECTS',
  GET_USER: 'GET_USER',
  REQUEST_SIGNIN: 'REQUEST_SIGNIN',
  REQUEST_SIGNOUT: 'REQUEST_SIGNOUT',
  REQUEST_SIGNUP: 'REQUEST_SIGNUP',
  UPDATE_USERINFO: 'UPDATE_USERINFO',
  GET_PROJECT: 'GET_PROJECT',
  EDIT_PROJECT: 'EDIT_PROJECT',
  UPDATE_PROJECTTITLE: 'UPDATE_PROJECTTITLE',
  DELETE_PROJECT: 'DELETE_PROJECT',
  GET_PROJECTFILES: 'GET_PROJECTFILES',
  RESET_PROJECTFILES: 'RESET_PROJECTFILES',
  RUN_PROJECT: 'RUN_PROJECT',
  GET_PROJECTASSETS: 'GET_PROJECTASSETS',
  GET_COURSES: 'GET_COURSES',
  GET_COURSE: 'GET_COURSE',
  GET_STUDY: 'GET_STUDY',
  ADD_USER_CODE: 'ADD_USER_CODE',
  GET_USER_CODES: 'GET_USER_CODES',
  GET_DOCUMENTS: 'GET_DOCUMENTS',
  EXECUTE_CODE: 'EXECUTE_CODE'
};
